#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "dotfiles installation script; BASEDIR is $BASEDIR"

# shell
ln -s -i ${BASEDIR}/.sh ~/.sh
ln -s -i ${BASEDIR}/.shell ~/.shell
ln -s -i ${BASEDIR}/.profile ~/.profile

#bash
ln -s -i ${BASEDIR}/.bash ~/.bash
ln -s -i ${BASEDIR}/.bash/rc ~/.bashrc
ln -s -i ${BASEDIR}/.bash/profile ~/.bash_profile
ln -s -i ${BASEDIR}/.bash/login ~/.bash_login
ln -s -i ${BASEDIR}/.bash/logout ~/.bash_logout

# zsh
ln -s -i ${BASEDIR}/.zsh/env ~/.zshenv
ln -s -i ${BASEDIR}/.zsh/interactive ~/.zshrc
ln -s -i ${BASEDIR}/.zsh/login ~/.zlogin
ln -s -i ${BASEDIR}/.zsh/logout ~/.zlogout
