#!/bin/bash

BASEDIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo "dotfiles installation script; BASEDIR is $BASEDIR"

# shell
ln -s ${BASEDIR}/.sh ~/.sh
ln -s ${BASEDIR}/.shell ~/.shell
ln -s ${BASEDIR}/.bash ~/.bash
ln -s ${BASEDIR}/.bashrc ~/.bashrc
ln -s ${BASEDIR}/.bash_profile ~/.bash_profile
ln -s ${BASEDIR}/.bash_logout ~/.bash_logout
ln -s ${BASEDIR}/.profile ~/.profile

# zsh
ln -s ${BASEDIR}/.zsh/env ~/.zshenv
ln -s ${BASEDIR}/.zsh/interactive ~/.zshrc
ln -s ${BASEDIR}/.zsh/login ~/.zlogin
ln -s ${BASEDIR}/.zsh/logout ~/.zlogout

