#!/bin/sh

BASEDIR="$(cd "$(dirname -- "$0")" && pwd)"
DOTDIR=~/.dotfiles

echo "BASEDIR is $BASEDIR; DOTDIR is $DOTDIR"

function link_to() {
    ln -sin ${DOTDIR}/$1 $2
}

ln -sin ${BASEDIR} ${DOTDIR}

# shell
link_to sh ~/.sh
link_to shell ~/.shell
link_to .profile ~/.profile

# bash
link_to bash ~/.bash
link_to bash/rc ~/.bashrc
link_to bash/profile ~/.bash_profile
link_to bash/login ~/.bash_login
link_to bash/logout ~/.bash_logout

# zsh
link_to zsh/env ~/.zshenv
link_to zsh/interactive ~/.zshrc
link_to zsh/login ~/.zlogin
link_to zsh/logout ~/.zlogout

# git
link_to .gitconfig ~/.gitconfig

# tmux
link_to .tmux.conf ~/.tmux.conf

# vim
link_to .vimrc ~/.vimrc
# run :PlugInstall from within vim

unset link_to
